project:
  type: website
  output-dir: _output

website:
  title: "Sample Quarto documentation"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true


